Repository the-bat-signal/rooted, pull requests merged in 2021-04, with the labels that each got.

#142 chore: build fragile skeleton of links query
  cd2e9946d1776d183789e02bd045f927.png
  client/components/Map.js
  client/components/SingleLanguage.js
  client/components/navbar.js
  package-lock.json
Labels: Tier 1

#174 Thursday
  client/components/MapLoader.js
  client/components/PopupBox.js
  client/components/SingleLanguage.js
  package-lock.json
  package.json
Labels: ~*~Design/Aesthetic~*~

#184 Aos
  client/components/LanguagePractice.js
  client/components/MapLoader.js
  client/components/PopupBox.js
  client/components/SingleLanguage.js
  client/components/StartPage.js
  client/routes.js
  package-lock.json
  public/languagePractice.css
  public/languagePractice.css.map
  public/languagePractice.scss
Labels: Tier 2, ~*~Design/Aesthetic~*~

#186 New branch
  client/components/Map.js
  client/components/MapToggles.js
  package-lock.json
Labels: Tier 2

#187 refactor: link to language practice
  client/components/Map.js
  client/components/PopupBox.js
  client/components/Practice.js
  client/components/SingleLanguage.js
  client/routes.js
Labels: Tier 2

#189 refactor/style: refactor: singleLanguage now makes a query to FS. sty…
  client/components/SingleLanguage.js
  client/components/navbar.js
  package-lock.json
  public/style.css
Labels: Tier 2, bug, ~*~Design/Aesthetic~*~

#190 chore: build LanguagePractice skeleton
  client/components/LanguagePractice.js
  client/components/SingleLanguage.js
Labels: Tier 2

#196 Feat: territory text layer, added some new colors to polygons, toggle…
  client/components/Map.js
Labels: ~*~Design/Aesthetic~*~

#198 Fix: fixed some database bugs
  client/components/Map.js
  client/components/Practice.js
  client/components/SingleLanguage.js
  package-lock.json
Labels: Tier 2

#202 Tier 2
  client/components/MapToggles.js
  client/components/PopupBox.js
  client/components/SingleLanguage.js
  package-lock.json
  public/style.css
Labels: Tier 2

#209 style: lots of colors and sounds
  client/components/LanguagePractice.js
  client/components/Map.js
  client/components/PopupBox.js
  client/components/SingleLanguage.js
  package-lock.json
  public/audio/Mohegan_vocab/Hello!.m4a
  public/audio/Mohegan_vocab/Nahunshásh! : Nahunsháq !.m4a
  public/audio/Mohegan_vocab/Nukôkicá..m4a
  public/audio/Mohegan_vocab/Táput ni!.m4a
  public/audio/Mohegan_vocab/Tôn kutayuw?.m4a
  public/audio/Mohegan_vocab/Tôn kutusuwis?.m4a
  public/audio/Mohegan_vocab/___ nuwisuwôk..m4a
  public/languagePractice.css
  public/languagePractice.css.map
  public/languagePractice.scss
Labels: Tier 2, ~*~Design/Aesthetic~*~

#213 Fix: database call fixes
  client/components/Map.js
  client/components/PopupBox.js
  client/components/SingleLanguage.js
  package-lock.json
Labels: bug

#216 Updatez
  client/components/Map.js
  client/components/PopupBox.js
  client/components/SingleLanguage.js
Labels: bug

#220 style: add AOS
  client/components/SingleLanguage.js
  public/languagePractice.css
  public/languagePractice.scss
  public/style.css
Labels: ~*~Design/Aesthetic~*~

#219 Fix: maybe fixed firestore calls??
  client/components/Map.js
  client/components/PopupBox.js
  client/components/SingleLanguage.js
  package-lock.json
Labels: bug

#223 Media
  client/components/SingleLanguage.js
  client/components/StartPage.js
  package-lock.json
  public/style.css
Labels: ~*~Design/Aesthetic~*~

#227 style: add color to right columns of single language
  package-lock.json
  public/style.css
Labels: ~*~Design/Aesthetic~*~

#228 3lijah
  client/components/Map.js
  client/components/navbar.js
Labels: bug

#232 Random
  client/components/LanguagePractice.js
  client/components/Map.js
  client/components/PopupBox.js
  client/components/SingleLanguage.js
  package-lock.json
  public/css/languagePractice.css
  public/languagePractice.scss
  public/style.css
Labels: bug

#236 Fix: actually fixed error
  public/languagePractice.css
Labels: bug, question

#238 fix: compile sass
  package-lock.json
  public/languagePractice.css
Labels: ~*~Design/Aesthetic~*~

#240 feat: add use effect
  client/components/LanguagePractice.js
Labels: Tier 2

#249 New branch
  package-lock.json
  public/style.css
Labels: bug

#255 style: adjust media query on language practice
  package-lock.json
  public/languagePractice.css
  public/languagePractice.scss
  public/style.css
Labels: ~*~Design/Aesthetic~*~

#258 New branch
  client/components/Map.js
  package-lock.json
Labels: bug
