Repository the-bat-signal/rooted, pull requests merged in 2021-03, with the labels that each got.

#23 Firestore test
  .firebaserc
  .gitignore
  firebase.json
  firestore.indexes.json
  firestore.js
  firestore.rules
  package-lock.json
  package.json
  rooted-e00eba1f3160.json
Labels: Tier 1

#26 Weekend firestore
  client/components/Map.js
  firebase.json
  package-lock.json
  package.json
  public/index.html
  server/firebase.js
Labels: Primary Proof of Concept

#27 Weekend map
  client/components/Map.js
  server/index.js
Labels: Primary Proof of Concept, Tier 1

#28 Feat: Additional PWA compliance
  public/index.html
  public/manifest.json
  public/offline.html
  public/serviceworker.js
Labels: Tier 1

#38 Firestore connection established
  client/app.js
  client/components/Map.js
  client/components/navbar.js
  client/data.js
  firestore.js
  firestore.rules
  package-lock.json
  package.json
  public/index.html
Labels: Tier 1

#46 Map layers
  client/components/Map.js
  client/components/OldMap.js
  client/components/SingleLanguage.js
  client/routes.js
  client/style.js
Labels: Tier 1, ~*~Design/Aesthetic~*~

#48 Map popup
  client/app.js
  client/components/Map.js
  client/components/OldMap.js
  client/components/Popup.js
  client/coordinates.js
  package.json
  public/index.html
  public/style.css
Labels: Tier 1

#47 Bug: working through buggy seed.js
  firestore.js
  public/seed.js
  public/territoriesData.js
  server/firebase.js
Labels: Tier 1

#50 fix: merge pull fix
  client/app.js
  client/components/Map.js
  client/components/oldMap.js
  server/firebase.js
Labels: Tier 1

#51 Fix: endless firestore calls resolved
  client/components/Map.js
Labels: bug

#52 Popup style
  client/components/Map.js
  client/components/Popup.js
  client/components/PopupBox.js
  client/coordinates.js
  public/style.css
Labels: Tier 1, ~*~Design/Aesthetic~*~

#53 Single lang view
  client/app.js
  client/components/SingleLanguage.js
Labels: Tier 1

#55 Thurs branch
  client/components/Map.js
  package-lock.json
  public/languagesData.js
  public/seed-lang.js
  public/seed.js
Labels: Tier 1

#57 Popup style
  client/components/Map.js
  client/components/PopupBox.js
  client/coordinates.js
Labels: Tier 1

#58 Polygons galore
  client/components/Map.js
Labels: Tier 1

#59 Chore: Building Start Page
  client/app.js
  client/components/Map.js
  client/components/StartPage.js
  client/routes.js
  package-lock.json
  package.json
Labels: Tier 2, ~*~Design/Aesthetic~*~

#60 Fix: popups for dynamically added polygon layers
  client/components/Map.js
  client/components/PopupBox.js
Labels: Tier 1

#64 Feat: Fancy Start Page
  client/components/StartPage.js
  client/routes.js
  package-lock.json
  public/favicon.ico
  public/images/icons-192.png
  public/images/icons-512.png
  public/style.css
Labels: ~*~Design/Aesthetic~*~

#66 Resize popup
  client/components/Map.js
  client/components/PopupBox.js
  client/components/SingleLanguage.js
  public/style.css
Labels: BETA TESTING, Tier 1, ~*~Design/Aesthetic~*~

#67 chore: single language compnent vocab db call
  client/components/SingleLanguage.js
Labels: Tier 1

#68 Feat: Changed initital view state of map
  client/components/Map.js
  client/components/PopupBox.js
  public/style.css
Labels: BETA TESTING

#69 feat: vocab appearing
  client/components/Map.js
  client/components/PopupBox.js
Labels: BETA TESTING, Tier 1

#70 Fix: Start Page & PopUp
  client/components/Map.js
  client/components/PopupBox.js
  client/components/StartPage.js
  public/style.css
Labels: BETA TESTING, ~*~Design/Aesthetic~*~

#71 refactor: single lang component to render info from props
  client/components/SingleLanguage.js
Labels: BETA TESTING, Tier 1

#72 Prebeta eli
  client/components/Map.js
  client/components/PopupBox.js
  package-lock.json
  public/style.css
Labels: bug

#73 fixed vocab in popups
  client/components/PopupBox.js
Labels: BETA TESTING

#74 refactor: basic vocab/phrases on single language component
  client/components/SingleLanguage.js
Labels: BETA TESTING, Tier 1

#80 Styling test
  client/components/Map.js
  client/components/PopupBox.js
  client/components/SingleLanguage.js
  client/components/index.js
  public/seed-territories.js
  public/style.css
Labels: ~*~Design/Aesthetic~*~

#94 Monday work
  client/components/Map.js
  client/components/PopupBox.js
  client/components/SingleLanguage.js
  client/components/StartPage.js
Labels: Tier 1

#96 Feat: hid API keys, changed setitngs of geolocateControl"
  client/components/Map.js
  public/seed-lang.js
  public/seed-territories.js
  server/firebase.js
Labels: bug

#99 final styles
  package-lock.json
Labels: ~*~Design/Aesthetic~*~

#120 Feat: accessed user's location onGeolocate and set state to that
  client/components/Map.js
  package-lock.json
  public/seed-lang.js
  public/style.css
Labels: bug

#129 About to merge
  client/components/Map.js
  client/components/PopupBox.js
  client/components/SingleLanguage.js
  package-lock.json
  package.json
  public/style.css
  webpack.config.js
Labels: Tier 1

#131 style: loading page
  client/components/Map.js
  package-lock.json
  public/style.css
Labels: Tier 1

#138 Toggle time
  client/components/Map.js
  package-lock.json
  public/style.css
Labels: bug
